### PR TITLE
Require WebKitGTK >= 2.12.0

### PR DESCRIPTION
**Pull request by jiri-janousek**
- Author: Jiří Janoušek janousek.jiri@gmail.com
- Reviewed by: FIXME <FIXME>
- Issue: tiliado/nuvola-app-soundcloud#4
- Issue: tiliado/nuvola-app-soundcloud#5

---

When merging this branch, please follow [Guidelines for Merge Commits](https://tiliado.github.io/nuvolaplayer/development/apps/guidelines.html#merge-commits), especially:
- Don't merge directly in GitHub as it produces a crappy commit message.
- The title of the pull request becomes the merge commit title (the first line of the merge commit).
- The description of the pull request up to the first horizontal separator/line becomes the merge commit body (separated from the title by a blank line).
- Fill in the `Reviewed by` line and add the `Pull Request` line.

### CODE REVIEW

**Comment by jiri-janousek** [comment]
Hello @kixam. If you agree with the proposed changed, but don't have time to merge them, let me know and I'll merge the branch by myself.

**Comment by kixam** [comment]
hello @fenryxo ,

it seems to me that most of the code you propose to add to the plugin might rather be integrated to the main software in some way? in particular, it seems to me you would have to duplicate similar code to several other plugins?

**Comment by jiri-janousek** [comment]
It may be integrated into the Nuvola Core eventually but not sooner than in NP 3.2. This is merely a hotfix for NP 3.0.

**Comment by kixam** [comment]
alright then, please merge

**Comment by jiri-janousek** [comment]
I'll probably get down to it tomorrow. May I create a new release after that or would you like to make some changes before the release?

**Comment by kixam** [comment]
I do not plan any change for now, please proceed

**Pull request merged**
